// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package database

import (
	"time"

	"github.com/google/uuid"
)

type Video struct {
	ID           uuid.UUID
	Title        string
	Description  string
	PublishedOn  time.Time
	ThumbnailUrl string
	Provider     string
}

type YoutubeVideo struct {
	ID            uuid.UUID
	Video         uuid.UUID
	VideoID       string
	ViewCount     int32
	LikeCount     int32
	FavoriteCount int32
	CommentCount  int32
}
