// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package database

import (
	"time"

	"github.com/google/uuid"
)

type Video struct {
	ID            uuid.UUID
	Title         string
	Description   string
	PublishedOn   time.Time
	ThumbnailUrl  string
	Provider      string
	VideoID       string
	ViewCount     int64
	LikeCount     int64
	FavoriteCount int64
	CommentCount  int64
}
