# version is now obsolete as of compose version 2.25 so I am not using that
services:
  database:
    image: postgres:latest
    ports:
      - "6500:5432"
    env_file:
      - .env
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
